/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm1;
import javax.swing.JOptionPane;
import java.awt.event.*;
import java.awt.*;

/**
 *
 * @author HEI
 */
public class open extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public open() {
        initComponents();
        History.initialHistory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        openWindow = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        txtName = new javax.swing.JTextField();
        singInbtn = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 300, 300, 300));
        setForeground(new java.awt.Color(0, 153, 0));
        setLocation(new java.awt.Point(300, 100));
        setMaximumSize(new java.awt.Dimension(300, 300));
        setPreferredSize(new java.awt.Dimension(300, 300));
        setResizable(false);
        setSize(new java.awt.Dimension(300, 300));
        setType(java.awt.Window.Type.POPUP);

        openWindow.setBackground(new java.awt.Color(153, 153, 0));

        title.setBackground(java.awt.Color.red);
        title.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        title.setText("ATM server");

        name.setBackground(new java.awt.Color(102, 102, 0));
        name.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        name.setText("Name:");

        pass.setBackground(new java.awt.Color(102, 102, 0));
        pass.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        pass.setText("Password:");

        txtPass.setBackground(new java.awt.Color(102, 102, 0));
        txtPass.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        txtPass.setForeground(new java.awt.Color(255, 255, 255));

        txtName.setBackground(new java.awt.Color(102, 102, 0));
        txtName.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        singInbtn.setBackground(new java.awt.Color(102, 102, 0));
        singInbtn.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        singInbtn.setForeground(new java.awt.Color(255, 255, 255));
        singInbtn.setText("sign in ");
        singInbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singInbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout openWindowLayout = new javax.swing.GroupLayout(openWindow);
        openWindow.setLayout(openWindowLayout);
        openWindowLayout.setHorizontalGroup(
            openWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(openWindowLayout.createSequentialGroup()
                .addGroup(openWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(openWindowLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(openWindowLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(openWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(openWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(singInbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(openWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtName)
                                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        openWindowLayout.setVerticalGroup(
            openWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(openWindowLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(title)
                .addGap(29, 29, 29)
                .addGroup(openWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(openWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(singInbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(openWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(openWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void test_user_name(String st) {
        if (!st.toLowerCase().equals(account.getName())) {
            JOptionPane.showMessageDialog(this, "unvaled user name!!Try again");
            txtName.setText("");
            txtPass.setText("");

        } else {
            test_user_password(txtPass.getText());
        }

    }

    public void test_user_password(String st) {
        if (!st.equals(account.getPass())) {
            test_user_password(JOptionPane.showInputDialog("unvalid password pleas enter your password again"));
        } else {
            closing();
            new types().setVisible(true);

        }
    }


    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
    }//GEN-LAST:event_txtNameActionPerformed


    private void singInbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singInbtnActionPerformed

        test_user_name(txtName.getText());


    }//GEN-LAST:event_singInbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    private void closing() {

        WindowEvent closing = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closing);

    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new open().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel name;
    private javax.swing.JPanel openWindow;
    private javax.swing.JLabel pass;
    private javax.swing.JButton singInbtn;
    private javax.swing.JLabel title;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
